/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class FrmVentas extends javax.swing.JFrame {

    private DefaultTableModel  dtm;
    private Object[] Cliente = new Object[5];
    private int filaSeleccionada;
    
    public FrmVentas() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        btncomprar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();
        txtprecio = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtfcompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administracion de ventas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cliente", "producto", "precio", "fechaCompra", "cantidad", "IVA", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Producto");

        btncomprar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btncomprar.setText("Comprar");
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Precio");

        btncargar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btncargar.setText("Cargar");
        btncargar.setEnabled(false);
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        btnmodificar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setEnabled(false);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setEnabled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Fecha compra");

        txtfcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcompraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Cantidad");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel8.setText("IVA 19%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtcantidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btncomprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel1)
                    .addGap(14, 14, 14)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(jLabel5)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncomprar)
                    .addComponent(btncargar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar))
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addContainerGap(490, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        String cliente = txtcliente.getText();
        String producto = txtproducto.getText();
        String precioStr = txtprecio.getText();
        String fechaCompra = txtfcompra.getText();
        String cantidad = txtcantidad.getText();

        if (cliente.isEmpty() || producto.isEmpty() || precioStr.isEmpty() ||
            fechaCompra.isEmpty() || cantidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos imcompletos, Por favor completarlos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double precio = Double.parseDouble(precioStr);
        int cantidads = Integer.parseInt(cantidad);

        // Calcular el IVA y el Total
        double subtotal = precio * cantidads;
        double iva = subtotal * 0.19;
        double total = subtotal + iva;

        Object[] fila = new Object[7];
        fila[0] = cliente;
        fila[1] = producto;
        fila[2] = String.format("%.2f", precio);
        fila[3] = fechaCompra;
        fila[4] = cantidad;
        fila[5] = String.format("%.2f", iva);
        fila[6] = String.format("%.2f", total);
        dtm.addRow(fila);

        txtcliente.setText("");
        txtproducto.setText("");
        txtprecio.setText("");
        txtfcompra.setText("");
        txtcantidad.setText("");
        txtcliente.requestFocus();

        btncomprar.setEnabled(true);
        btneliminar.setEnabled(true);
        btncargar.setEnabled(true);
        
        
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Registro no seleccionado", "Error al modificar el registro", JOptionPane.WARNING_MESSAGE);
        }else{
            filaSeleccionada = jTable1.getSelectedRow();
            txtcliente.setText(dtm.getValueAt(jTable1.getSelectedRow(),0).toString());
            txtproducto.setText(dtm.getValueAt(jTable1.getSelectedRow(),1).toString());
            txtprecio.setText(dtm.getValueAt(jTable1.getSelectedRow(),2).toString());
            txtfcompra.setText(dtm.getValueAt(jTable1.getSelectedRow(),3).toString());
            txtcantidad.setText(dtm.getValueAt(jTable1.getSelectedRow(),4).toString());
            txtcliente.requestFocus();

            btncomprar.setEnabled(false);
            btncargar.setEnabled(false);
            btneliminar.setEnabled(false);
            btnmodificar.setEnabled(true);
        }
    }//GEN-LAST:event_btncargarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();

if (filaSeleccionada == -1) {
    JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para realizar la modificación.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Obteniendo y limpiando los datos de los campos de texto
String cliente = txtcliente.getText().trim();
String producto = txtproducto.getText().trim();
String precioStr = txtprecio.getText().trim();
String fechaCompra = txtfcompra.getText().trim();
String cantidad = txtcantidad.getText().trim();

// Verificación de que todos los campos estén completos
if (cliente.isEmpty() || producto.isEmpty() || precioStr.isEmpty() || fechaCompra.isEmpty() || cantidad.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "Advertencia", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    // Conversión de los valores numéricos y cálculo de IVA y total
    double precio = Double.parseDouble(precioStr);
    int cantidads = Integer.parseInt(cantidad);

    double subtotal = precio * cantidads;
    double iva = subtotal * 0.19;
    double total = subtotal + iva;

    // Actualización de los valores en la tabla
    dtm.setValueAt(cliente, filaSeleccionada, 0);
    dtm.setValueAt(producto, filaSeleccionada, 1);
    dtm.setValueAt(String.format("%.2f", precio), filaSeleccionada, 2);
    dtm.setValueAt(fechaCompra, filaSeleccionada, 3);
    dtm.setValueAt(cantidad, filaSeleccionada, 4);
    dtm.setValueAt(String.format("%.2f", iva), filaSeleccionada, 5);
    dtm.setValueAt(String.format("%.2f", total), filaSeleccionada, 6);

    // Limpiar los campos de texto y restablecer el foco
    txtcliente.setText("");
    txtproducto.setText("");
    txtprecio.setText("");
    txtfcompra.setText("");
    txtcantidad.setText("");
    txtcliente.requestFocus();

    // Habilitar/deshabilitar botones según la acción
    btncomprar.setEnabled(true);
    btncargar.setEnabled(true);
    btneliminar.setEnabled(true);
    btnmodificar.setEnabled(false);

} catch (NumberFormatException e) {
    // Mostrar mensaje de error si hay un problema con la conversión numérica
    JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para el precio y la cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Ningun registro seleccionado", "ERRROR ELIMINAR REGISTRO", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showConfirmDialog(null, "Quieres eliminar este registro?", "CONFIRMACION DE ELIMINACION", JOptionPane.YES_NO_OPTION);
            dtm.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtfcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtfcompra;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
}
